from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import cv2


def random_crop(image, min_ratio=0.4, max_ratio=1.0):
    """
    对图片随机0.4~1.0比率大小的区域裁剪，保持长宽比不变
    :param image:原图
    :param min_ratio:
    :param max_ratio:
    :return:裁剪后图片
    """
    h, w = image.shape[:2]

    ratio = random.random()

    scale = min_ratio + ratio * (max_ratio - min_ratio)

    new_h = int(h * scale)
    new_w = int(w * scale)

    y = np.random.randint(0, h - new_h)
    x = np.random.randint(0, w - new_w)

    image = image[y:y + new_h, x:x + new_w, :]

    return image


def crop(image):
    """
    先随机水平翻转，再裁剪图片，并保存
    :param image:
    :return:
    """
    crop_times = 30    # 对于一张图随机裁剪20次，次数可修改
    for i in range(crop_times):
        axis = np.random.randint(low=-1, high=2)
        # axis 0 垂直翻转，1水平翻转 ，-1水平垂直翻转，2不翻转，各自以25%的可能性
        if axis != 2:
            image = cv2.flip(image, axis)
        image_trans = random_crop(image)
        try:
            image_name_new = image_name.split('.')[0]+'_crop_'+str(i)+'.jpg'
            cv2.imwrite(os.path.join(save_path, image_name_new), image_trans)
            print("{} success generated by {}, change to {}."
                  .format(image_name_new, "random_crop", image_trans.shape))
        except:
            print("error")


if __name__ == "__main__":
    image_root_path = r"G:\xqy\faster_rcnn\TGK_DATASET\JPEGImages"      # 修改图片根目录
    # image_name = "fpccrease_7.jpg"

    dir = os.listdir(image_root_path)
    file_number = (len(dir))

    index = 1
    for f in dir:
        image_name = f
        image = cv2.imread(os.path.join(image_root_path, image_name))
        print("File [{}/{}], init image size is {}".format(index, file_number, image.shape))
        index = index + 1
        print("-------------------------------------------------")

        save_path = r".\TGK_DATASET\JPEGImages" # 图像保存路径
        if not os.path.exists(save_path):
            os.makedirs(save_path)

        crop(image)
        print("-------------------------------------------------")



